# Generated by Django 2.2.6 on 2022-04-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_auto_20220423_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='event',
            new_name='event_id',
        ),
    ]
