# Generated by Django 2.2.6 on 2022-04-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_auto_20220423_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description_text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
