# Generated by Django 2.2.6 on 2022-04-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_auto_20220424_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
